### ISSUE TITLE
[Feature Request] TW5-TaskList - Filtered views to improve how users can manage large numbers of items

### ISSUE THREAD

**Issue by SonephetR2** [EvidentlyCube/TW5-PluginShowcase#7] opened 2024-08-30 07:50 UTC
## The problem

Currently, the TW5-TaskList plugin presents all tasks/action items in a single view, which can be overwhelming for users with numerous tasks. While it's possible to use tiddler filters on TaskList items, this approach results in static list views that lacks the interactive features of the main UI, such as the ability to add or edit new tasks on the fly.

## Description of the desired feature

The plugin should provide filtered views to filter items based on any field corresponding to user-relevant criteria (e.g., time period, theme), with the possibility of easily switching between different filtered views without creating and maintaining separate lists and, ideally, also allowing for the transclusion of filtered views.

This would enable users to improve focus by presenting manageable subsets of tasks without the need to create and manage multiple separate lists.

## Example use cases

* I can enhance project summary tiddlers by appending all pending action items within that very same tiddler.
* I can have a GTD-style view template that highlights tasks for today without presenting the hundreds of tasks I have as upcoming or deferred (parking lot).
* I can filter out non-work-related items while at work, and filter out work-related items after work.

----

I'd highly appreciate any pointers in that general direction :)

(As an aside, I'm blown away by the versatility of your seemingly little-known todo plugin. Kudos and thanks for the great tool!)

**Comment by EvidentlyCube** [comment] 2024-09-17 08:06
The problem is that the task list was always meant to be for small lists of tasks, think shopping list, stuff for today - not a semi-fledged replacement for Jira.

I think the most flexible solution would be to extend `<<ec-task-list>>` macro to accept filter extensions so you can filter the resultset by yourself. I'll see about implementing it.

**Comment by EvidentlyCube** [comment] 2024-09-17 10:52
@SonephetR2 I've implemented something!

https://evidentlycube.github.io/TW5-PluginShowcase/#Task%20List%20Showcase%20-%20Dynamic%20Filtering

With this you can do pretty much anything you want so hopefully you'll be able to built whatever views or filters you want.

I am marking this as done but feel free to leave further questions/comments, it can still be reopened.

**Closed by EvidentlyCube** 2024-09-17 10:52 UTC

**Comment by SonephetR2** [comment] 2024-09-18 10:22
Thank you so much!! It works great! ![2024-09-18_12-20](https://github.com/user-attachments/assets/e95978d0-acda-4d67-a038-507a1e4c840e)
